## Process the CG model of PDB file generated by cafemol initial run
## Does coordiante centering based on cafemol input afm and pdb formatting 
## for preparing the pdb file for Cafemol AFM fit run
## Usage: Rscript process_pdb_cg.R input.pdb cafemol_input_file

# install.packages("bio3d")
library(bio3d)
library(dplyr)
library(stringr)

#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
#print(args[1])
#length(args)
## test if there is at least one argument: if not, return an error
if (length(args)==0) {
  stop("Please provide the initial PDB file", call.=FALSE)
}

## Read input pdb
input.pdb = args[1]
pdb = read.pdb2(input.pdb)

## Read cafemol input file
file = args[2]
data.lines = readLines(file)[grep("AFM_IMAGE", readLines(file))]
data.inp =  data.lines %>%
  strsplit("\\s+") %>%
  do.call(rbind, .) %>%
  data.frame()

# head(data.inp)
x.CM = sum(as.numeric(data.inp$X2))/nrow(data.inp)
y.CM = sum(as.numeric(data.inp$X3))/nrow(data.inp)

x.pdb.CM = sum(pdb$atom$x)/length(pdb$atom$x)
y.pdb.CM = sum(pdb$atom$y)/length(pdb$atom$y)

pdb$atom$x =  pdb$atom$x + (x.CM - x.pdb.CM)
pdb$atom$y =  pdb$atom$y + (y.CM - y.pdb.CM)
pdb$atom$z =  pdb$atom$z - min(pdb$atom$z)
x.pdb.CM = sum(pdb$atom$x)/length(pdb$atom$x)
y.pdb.CM = sum(pdb$atom$y)/length(pdb$atom$y)
z.pdb.CM = sum(pdb$atom$z)/length(pdb$atom$z)

xyz.mat = cbind(pdb$atom$x, pdb$atom$y, pdb$atom$z )
xyz.vec = as.vector(t(xyz.mat))
## set the spacing with respect to resid
pdb$atom$resid = paste0(pdb$atom$resid, " ")
# write the new pdb object to file
out.pdb = paste0(tools::file_path_sans_ext(basename(input.pdb)),"_center.pdb")
write.pdb(pdb, xyz=xyz.vec, 
          file=out.pdb)




